eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-one/**
      serviceId: service-one
    api-b:
      path: /api-two/**
      serviceId: service-two
  ribbon:
    eager-load:
      #开启zuul网关的立即加载（在zt调试很久）
      enabled: true
  #ignored-services: *

#网关负载均衡超时时间（路由到其他服务的时间）
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000