eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-one/**
      serviceId: service-one
    api-b:
      path: /api-two/**
      serviceId: service-two